---
title: "Omictools Visualization"
author: "gahoolee"
date: "Friday, August 28, 2015"
output: html_document
runtime: shiny
---


```{r, echo=FALSE, eval=T, warning=FALSE, message=FALSE}
library(shiny)
library(jsonlite)
library(d3treeR)
library(DT)
library(reshape2)
library(dplyr)
load('omictools.RData')
load('omictools_tree.RData')
software_df<-software_df %>%
  mutate(id = gsub('^.*-', '', gsub('.html', '', omictools_link)) )

ui <- fluidPage(fluidRow(
  column(6,
         d3tree2Output( 'tree' ),
         textOutput( "clickedinfo", container = p ),
         DT::dataTableOutput('catalog')),
  column(6, DT::dataTableOutput('detail'))
  #textOutput( "detail", container = p )
  )
)

server <- function( input, output, session ){
  output$tree <- renderD3tree2({
    d3tree2(toJSON(omictools, auto_unbox = T),
            celltext = "name")
  })

  # from https://github.com/rstudio/leaflet/blob/master/inst/examples/shiny.R
  v <- reactiveValues(table = NULL)

  observeEvent(input$tree_click, {
    v$table <- subset(catalog_tree_df, parent.name == input$tree_click$name)
    
    if(nrow(v$table)==0){
      v$table <- subset(software_tree_df, parent.name == input$tree_click$name)
    }
  })

  output$clickedinfo <- renderText(input$tree_click$name)
  output$catalog <- DT::renderDataTable({
    datatable(v$table, selection = 'single') %>%
      formatStyle(
        'size',
        background = styleColorBar(v$table$size, 'steelblue'),
        backgroundSize = '100% 90%',
        backgroundRepeat = 'no-repeat',
        backgroundPosition = 'center'
      )
    })
  output$detail <- DT::renderDataTable({
    sid = v$table[input$catalog_row_last_clicked,]$id
    message(sid)
    
    software_df %>%
      filter(id == sid) %>%
      melt(id.vars='omictools_link', na.rm=T) %>%
      select(-omictools_link) %>%
      datatable %>%
      formatStyle('variable', fontWeight='bold')
    })
}

shinyApp( ui, server,
          options=list(
            width="100%", height="1440")
          )
```

```{r, echo=FALSE, eval=FALSE}
library(jsonlite)
library(d3treeR)
library(DT)
library(listviewer)
library(reshape2)
load('omictools_tree.RData')

renderD3tree2({
    d3tree2(toJSON(omictools, auto_unbox = T),
            celltext = "name")
  })

msg<-paste0(ls(), collapse = '\t')
selectInput('variables', 'variables',
            choices=ls(),
            selected=NULL)

v <- reactiveValues(msg = msg,
                    table = NULL,
                    m = list(aa=1))

renderJsonedit({
  jsonedit(get(input$variables))
  })

observeEvent(input$tree_click, {
  v$msg <- input$tree_click$name
  v$table <- subset(software_tree_df, parent.name == input$tree_click$name)
})

renderText(input$tree_click$name)

DT::renderDataTable(v$table)
```
